### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by pixelspezi** [dweidner/kirby-appkit#1]
Hey,
das Starter-Kit ist echt super.

Wollte dich fragen, ob du evtl. eine aktualisierte Version hast oder das noch aktuell ist?

Grüße

**Comment by dweidner** [comment]
Ich habe es schon länger nicht benutzt, und hätte auch nicht gedacht, dass es jemand anderes außer mir jemals nutzen würde. Meinst du ein Update des Tookits? Das sollte relativ problemlos möglich sein...

**Comment by pixelspezi** [comment]
Jain, Toolkit und deine "Blueprint"-App.
Für mich zum Einstieg war dein Beispiel richtig gut.
Habe mich jetzt doch für ein CMS entschieden sodass ich es nicht mehr benötige.

Danke dir :)
